/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaMediaItemIdRouteImport } from './routes/media.$mediaItemId'
import { Route as LibraryLibraryIdRouteImport } from './routes/library.$libraryId'

const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaMediaItemIdRoute = MediaMediaItemIdRouteImport.update({
  id: '/media/$mediaItemId',
  path: '/media/$mediaItemId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLibraryIdRoute = LibraryLibraryIdRouteImport.update({
  id: '/library/$libraryId',
  path: '/library/$libraryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shows': typeof ShowsRoute
  '/library/$libraryId': typeof LibraryLibraryIdRoute
  '/media/$mediaItemId': typeof MediaMediaItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shows': typeof ShowsRoute
  '/library/$libraryId': typeof LibraryLibraryIdRoute
  '/media/$mediaItemId': typeof MediaMediaItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movies': typeof MoviesRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shows': typeof ShowsRoute
  '/library/$libraryId': typeof LibraryLibraryIdRoute
  '/media/$mediaItemId': typeof MediaMediaItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movies'
    | '/settings'
    | '/setup'
    | '/shows'
    | '/library/$libraryId'
    | '/media/$mediaItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movies'
    | '/settings'
    | '/setup'
    | '/shows'
    | '/library/$libraryId'
    | '/media/$mediaItemId'
  id:
    | '__root__'
    | '/'
    | '/movies'
    | '/settings'
    | '/setup'
    | '/shows'
    | '/library/$libraryId'
    | '/media/$mediaItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoviesRoute: typeof MoviesRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShowsRoute: typeof ShowsRoute
  LibraryLibraryIdRoute: typeof LibraryLibraryIdRoute
  MediaMediaItemIdRoute: typeof MediaMediaItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$mediaItemId': {
      id: '/media/$mediaItemId'
      path: '/media/$mediaItemId'
      fullPath: '/media/$mediaItemId'
      preLoaderRoute: typeof MediaMediaItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$libraryId': {
      id: '/library/$libraryId'
      path: '/library/$libraryId'
      fullPath: '/library/$libraryId'
      preLoaderRoute: typeof LibraryLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoviesRoute: MoviesRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShowsRoute: ShowsRoute,
  LibraryLibraryIdRoute: LibraryLibraryIdRoute,
  MediaMediaItemIdRoute: MediaMediaItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
