/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsSchedulesRouteImport } from './routes/settings.schedules'
import { Route as SettingsPlaybackRouteImport } from './routes/settings.playback'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsNetworkRouteImport } from './routes/settings.network'
import { Route as SettingsMetadataSourcesRouteImport } from './routes/settings.metadata-sources'
import { Route as SettingsLogsRouteImport } from './routes/settings.logs'
import { Route as SettingsLiveTvRouteImport } from './routes/settings.live-tv'
import { Route as SettingsLibraryRouteImport } from './routes/settings.library'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDlnaRouteImport } from './routes/settings.dlna'
import { Route as SettingsDevicesRouteImport } from './routes/settings.devices'
import { Route as SettingsDatabaseRouteImport } from './routes/settings.database'
import { Route as SettingsConsoleRouteImport } from './routes/settings.console'
import { Route as PlayIdRouteImport } from './routes/play.$id'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as SettingsMetadataIndexRouteImport } from './routes/settings.metadata.index'
import { Route as SettingsMetadataIdRouteImport } from './routes/settings.metadata.$id'
import { Route as AppPersonIdRouteImport } from './routes/_app.person.$id'
import { Route as AppMediaIdRouteImport } from './routes/_app.media.$id'
import { Route as AppLibraryIdRouteImport } from './routes/_app.library.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSchedulesRoute = SettingsSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPlaybackRoute = SettingsPlaybackRouteImport.update({
  id: '/playback',
  path: '/playback',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNetworkRoute = SettingsNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadataSourcesRoute = SettingsMetadataSourcesRouteImport.update({
  id: '/metadata-sources',
  path: '/metadata-sources',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLiveTvRoute = SettingsLiveTvRouteImport.update({
  id: '/live-tv',
  path: '/live-tv',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLibraryRoute = SettingsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDlnaRoute = SettingsDlnaRouteImport.update({
  id: '/dlna',
  path: '/dlna',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDatabaseRoute = SettingsDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConsoleRoute = SettingsConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => SettingsRoute,
} as any)
const PlayIdRoute = PlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const SettingsMetadataIndexRoute = SettingsMetadataIndexRouteImport.update({
  id: '/metadata/',
  path: '/metadata/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadataIdRoute = SettingsMetadataIdRouteImport.update({
  id: '/metadata/$id',
  path: '/metadata/$id',
  getParentRoute: () => SettingsRoute,
} as any)
const AppPersonIdRoute = AppPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaIdRoute = AppMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIdRoute = AppLibraryIdRouteImport.update({
  id: '/library/$id',
  path: '/library/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/favorites': typeof AppFavoritesRoute
  '/search': typeof AppSearchRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/console': typeof SettingsConsoleRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/dlna': typeof SettingsDlnaRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/live-tv': typeof SettingsLiveTvRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata-sources': typeof SettingsMetadataSourcesRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/playback': typeof SettingsPlaybackRoute
  '/settings/schedules': typeof SettingsSchedulesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/': typeof SettingsIndexRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/media/$id': typeof AppMediaIdRoute
  '/person/$id': typeof AppPersonIdRoute
  '/settings/metadata/$id': typeof SettingsMetadataIdRoute
  '/settings/metadata/': typeof SettingsMetadataIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/favorites': typeof AppFavoritesRoute
  '/search': typeof AppSearchRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/console': typeof SettingsConsoleRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/dlna': typeof SettingsDlnaRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/live-tv': typeof SettingsLiveTvRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata-sources': typeof SettingsMetadataSourcesRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/playback': typeof SettingsPlaybackRoute
  '/settings/schedules': typeof SettingsSchedulesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/users': typeof SettingsUsersRoute
  '/': typeof AppIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/media/$id': typeof AppMediaIdRoute
  '/person/$id': typeof AppPersonIdRoute
  '/settings/metadata/$id': typeof SettingsMetadataIdRoute
  '/settings/metadata': typeof SettingsMetadataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/search': typeof AppSearchRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/console': typeof SettingsConsoleRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/dlna': typeof SettingsDlnaRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/live-tv': typeof SettingsLiveTvRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata-sources': typeof SettingsMetadataSourcesRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/playback': typeof SettingsPlaybackRoute
  '/settings/schedules': typeof SettingsSchedulesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/users': typeof SettingsUsersRoute
  '/_app/': typeof AppIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_app/library/$id': typeof AppLibraryIdRoute
  '/_app/media/$id': typeof AppMediaIdRoute
  '/_app/person/$id': typeof AppPersonIdRoute
  '/settings/metadata/$id': typeof SettingsMetadataIdRoute
  '/settings/metadata/': typeof SettingsMetadataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/setup'
    | '/favorites'
    | '/search'
    | '/play/$id'
    | '/settings/console'
    | '/settings/database'
    | '/settings/devices'
    | '/settings/dlna'
    | '/settings/general'
    | '/settings/library'
    | '/settings/live-tv'
    | '/settings/logs'
    | '/settings/metadata-sources'
    | '/settings/network'
    | '/settings/notifications'
    | '/settings/playback'
    | '/settings/schedules'
    | '/settings/security'
    | '/settings/users'
    | '/settings/'
    | '/library/$id'
    | '/media/$id'
    | '/person/$id'
    | '/settings/metadata/$id'
    | '/settings/metadata/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/favorites'
    | '/search'
    | '/play/$id'
    | '/settings/console'
    | '/settings/database'
    | '/settings/devices'
    | '/settings/dlna'
    | '/settings/general'
    | '/settings/library'
    | '/settings/live-tv'
    | '/settings/logs'
    | '/settings/metadata-sources'
    | '/settings/network'
    | '/settings/notifications'
    | '/settings/playback'
    | '/settings/schedules'
    | '/settings/security'
    | '/settings/users'
    | '/'
    | '/settings'
    | '/library/$id'
    | '/media/$id'
    | '/person/$id'
    | '/settings/metadata/$id'
    | '/settings/metadata'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/settings'
    | '/setup'
    | '/_app/favorites'
    | '/_app/search'
    | '/play/$id'
    | '/settings/console'
    | '/settings/database'
    | '/settings/devices'
    | '/settings/dlna'
    | '/settings/general'
    | '/settings/library'
    | '/settings/live-tv'
    | '/settings/logs'
    | '/settings/metadata-sources'
    | '/settings/network'
    | '/settings/notifications'
    | '/settings/playback'
    | '/settings/schedules'
    | '/settings/security'
    | '/settings/users'
    | '/_app/'
    | '/settings/'
    | '/_app/library/$id'
    | '/_app/media/$id'
    | '/_app/person/$id'
    | '/settings/metadata/$id'
    | '/settings/metadata/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  PlayIdRoute: typeof PlayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/schedules': {
      id: '/settings/schedules'
      path: '/schedules'
      fullPath: '/settings/schedules'
      preLoaderRoute: typeof SettingsSchedulesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/playback': {
      id: '/settings/playback'
      path: '/playback'
      fullPath: '/settings/playback'
      preLoaderRoute: typeof SettingsPlaybackRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/network': {
      id: '/settings/network'
      path: '/network'
      fullPath: '/settings/network'
      preLoaderRoute: typeof SettingsNetworkRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata-sources': {
      id: '/settings/metadata-sources'
      path: '/metadata-sources'
      fullPath: '/settings/metadata-sources'
      preLoaderRoute: typeof SettingsMetadataSourcesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logs': {
      id: '/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SettingsLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/live-tv': {
      id: '/settings/live-tv'
      path: '/live-tv'
      fullPath: '/settings/live-tv'
      preLoaderRoute: typeof SettingsLiveTvRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/library': {
      id: '/settings/library'
      path: '/library'
      fullPath: '/settings/library'
      preLoaderRoute: typeof SettingsLibraryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dlna': {
      id: '/settings/dlna'
      path: '/dlna'
      fullPath: '/settings/dlna'
      preLoaderRoute: typeof SettingsDlnaRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/devices': {
      id: '/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof SettingsDevicesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/database': {
      id: '/settings/database'
      path: '/database'
      fullPath: '/settings/database'
      preLoaderRoute: typeof SettingsDatabaseRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/console': {
      id: '/settings/console'
      path: '/console'
      fullPath: '/settings/console'
      preLoaderRoute: typeof SettingsConsoleRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/settings/metadata/': {
      id: '/settings/metadata/'
      path: '/metadata'
      fullPath: '/settings/metadata/'
      preLoaderRoute: typeof SettingsMetadataIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata/$id': {
      id: '/settings/metadata/$id'
      path: '/metadata/$id'
      fullPath: '/settings/metadata/$id'
      preLoaderRoute: typeof SettingsMetadataIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_app/person/$id': {
      id: '/_app/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof AppPersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media/$id': {
      id: '/_app/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof AppMediaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$id': {
      id: '/_app/library/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof AppLibraryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLibraryIdRoute: typeof AppLibraryIdRoute
  AppMediaIdRoute: typeof AppMediaIdRoute
  AppPersonIdRoute: typeof AppPersonIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFavoritesRoute: AppFavoritesRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppLibraryIdRoute: AppLibraryIdRoute,
  AppMediaIdRoute: AppMediaIdRoute,
  AppPersonIdRoute: AppPersonIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SettingsRouteChildren {
  SettingsConsoleRoute: typeof SettingsConsoleRoute
  SettingsDatabaseRoute: typeof SettingsDatabaseRoute
  SettingsDevicesRoute: typeof SettingsDevicesRoute
  SettingsDlnaRoute: typeof SettingsDlnaRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsLibraryRoute: typeof SettingsLibraryRoute
  SettingsLiveTvRoute: typeof SettingsLiveTvRoute
  SettingsLogsRoute: typeof SettingsLogsRoute
  SettingsMetadataSourcesRoute: typeof SettingsMetadataSourcesRoute
  SettingsNetworkRoute: typeof SettingsNetworkRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPlaybackRoute: typeof SettingsPlaybackRoute
  SettingsSchedulesRoute: typeof SettingsSchedulesRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsMetadataIdRoute: typeof SettingsMetadataIdRoute
  SettingsMetadataIndexRoute: typeof SettingsMetadataIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsConsoleRoute: SettingsConsoleRoute,
  SettingsDatabaseRoute: SettingsDatabaseRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  SettingsDlnaRoute: SettingsDlnaRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsLibraryRoute: SettingsLibraryRoute,
  SettingsLiveTvRoute: SettingsLiveTvRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsMetadataSourcesRoute: SettingsMetadataSourcesRoute,
  SettingsNetworkRoute: SettingsNetworkRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPlaybackRoute: SettingsPlaybackRoute,
  SettingsSchedulesRoute: SettingsSchedulesRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsMetadataIdRoute: SettingsMetadataIdRoute,
  SettingsMetadataIndexRoute: SettingsMetadataIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  PlayIdRoute: PlayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
