/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as PlayIdRouteImport } from './routes/play.$id'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppMetadataIndexRouteImport } from './routes/_app.metadata.index'
import { Route as AppMetadataIdRouteImport } from './routes/_app.metadata.$id'
import { Route as AppMediaIdRouteImport } from './routes/_app.media.$id'
import { Route as AppLibraryIdRouteImport } from './routes/_app.library.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PlayIdRoute = PlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppMetadataIndexRoute = AppMetadataIndexRouteImport.update({
  id: '/metadata/',
  path: '/metadata/',
  getParentRoute: () => AppRoute,
} as any)
const AppMetadataIdRoute = AppMetadataIdRouteImport.update({
  id: '/metadata/$id',
  path: '/metadata/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaIdRoute = AppMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIdRoute = AppLibraryIdRouteImport.update({
  id: '/library/$id',
  path: '/library/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/search': typeof AppSearchRoute
  '/play/$id': typeof PlayIdRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/media/$id': typeof AppMediaIdRoute
  '/metadata/$id': typeof AppMetadataIdRoute
  '/metadata/': typeof AppMetadataIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/search': typeof AppSearchRoute
  '/play/$id': typeof PlayIdRoute
  '/': typeof AppIndexRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/media/$id': typeof AppMediaIdRoute
  '/metadata/$id': typeof AppMetadataIdRoute
  '/metadata': typeof AppMetadataIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/_app/search': typeof AppSearchRoute
  '/play/$id': typeof PlayIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/library/$id': typeof AppLibraryIdRoute
  '/_app/media/$id': typeof AppMediaIdRoute
  '/_app/metadata/$id': typeof AppMetadataIdRoute
  '/_app/metadata/': typeof AppMetadataIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/search'
    | '/play/$id'
    | '/library/$id'
    | '/media/$id'
    | '/metadata/$id'
    | '/metadata/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/search'
    | '/play/$id'
    | '/'
    | '/library/$id'
    | '/media/$id'
    | '/metadata/$id'
    | '/metadata'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/settings'
    | '/_app/search'
    | '/play/$id'
    | '/_app/'
    | '/_app/library/$id'
    | '/_app/media/$id'
    | '/_app/metadata/$id'
    | '/_app/metadata/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  PlayIdRoute: typeof PlayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metadata/': {
      id: '/_app/metadata/'
      path: '/metadata'
      fullPath: '/metadata/'
      preLoaderRoute: typeof AppMetadataIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metadata/$id': {
      id: '/_app/metadata/$id'
      path: '/metadata/$id'
      fullPath: '/metadata/$id'
      preLoaderRoute: typeof AppMetadataIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media/$id': {
      id: '/_app/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof AppMediaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$id': {
      id: '/_app/library/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof AppLibraryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLibraryIdRoute: typeof AppLibraryIdRoute
  AppMediaIdRoute: typeof AppMediaIdRoute
  AppMetadataIdRoute: typeof AppMetadataIdRoute
  AppMetadataIndexRoute: typeof AppMetadataIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppLibraryIdRoute: AppLibraryIdRoute,
  AppMediaIdRoute: AppMediaIdRoute,
  AppMetadataIdRoute: AppMetadataIdRoute,
  AppMetadataIndexRoute: AppMetadataIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  PlayIdRoute: PlayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
