/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PlayIdRouteImport } from './routes/play/$id'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedLibraryBrowserRouteImport } from './routes/_authenticated/library-browser'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedLiveTvRouteRouteImport } from './routes/_authenticated/live-tv/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedLiveTvIndexRouteImport } from './routes/_authenticated/live-tv/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsSubtitlesRouteImport } from './routes/_authenticated/settings/subtitles'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsSchedulesRouteImport } from './routes/_authenticated/settings/schedules'
import { Route as AuthenticatedSettingsScanExclusionsRouteImport } from './routes/_authenticated/settings/scan-exclusions'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsPluginsRouteImport } from './routes/_authenticated/settings/plugins'
import { Route as AuthenticatedSettingsPlaybackRouteImport } from './routes/_authenticated/settings/playback'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsNetworkRouteImport } from './routes/_authenticated/settings/network'
import { Route as AuthenticatedSettingsMetadataSourcesRouteImport } from './routes/_authenticated/settings/metadata-sources'
import { Route as AuthenticatedSettingsLogsRouteImport } from './routes/_authenticated/settings/logs'
import { Route as AuthenticatedSettingsLiveTvRouteImport } from './routes/_authenticated/settings/live-tv'
import { Route as AuthenticatedSettingsLibraryRouteImport } from './routes/_authenticated/settings/library'
import { Route as AuthenticatedSettingsJobsRouteImport } from './routes/_authenticated/settings/jobs'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsDlnaRouteImport } from './routes/_authenticated/settings/dlna'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsDevicesRouteImport } from './routes/_authenticated/settings/devices'
import { Route as AuthenticatedSettingsConsoleRouteImport } from './routes/_authenticated/settings/console'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedPersonIdRouteImport } from './routes/_authenticated/person/$id'
import { Route as AuthenticatedMediaIdRouteImport } from './routes/_authenticated/media/$id'
import { Route as AuthenticatedLiveTvChannelIdRouteImport } from './routes/_authenticated/live-tv/$channelId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedSettingsOperationsRouteRouteImport } from './routes/_authenticated/settings/operations/route'
import { Route as AuthenticatedSettingsOperationsIndexRouteImport } from './routes/_authenticated/settings/operations/index'
import { Route as AuthenticatedSettingsMetadataIndexRouteImport } from './routes/_authenticated/settings/metadata/index'
import { Route as AuthenticatedSettingsOperationsManageRouteImport } from './routes/_authenticated/settings/operations/manage'
import { Route as AuthenticatedSettingsMetadataIdRouteImport } from './routes/_authenticated/settings/metadata/$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlayIdRoute = PlayIdRouteImport.update({
  id: '/play/$id',
  path: '/play/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryBrowserRoute =
  AuthenticatedLibraryBrowserRouteImport.update({
    id: '/library-browser',
    path: '/library-browser',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveTvRouteRoute =
  AuthenticatedLiveTvRouteRouteImport.update({
    id: '/live-tv',
    path: '/live-tv',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedLiveTvIndexRoute =
  AuthenticatedLiveTvIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLiveTvRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSubtitlesRoute =
  AuthenticatedSettingsSubtitlesRouteImport.update({
    id: '/subtitles',
    path: '/subtitles',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSchedulesRoute =
  AuthenticatedSettingsSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsScanExclusionsRoute =
  AuthenticatedSettingsScanExclusionsRouteImport.update({
    id: '/scan-exclusions',
    path: '/scan-exclusions',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPluginsRoute =
  AuthenticatedSettingsPluginsRouteImport.update({
    id: '/plugins',
    path: '/plugins',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsPlaybackRoute =
  AuthenticatedSettingsPlaybackRouteImport.update({
    id: '/playback',
    path: '/playback',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNetworkRoute =
  AuthenticatedSettingsNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsMetadataSourcesRoute =
  AuthenticatedSettingsMetadataSourcesRouteImport.update({
    id: '/metadata-sources',
    path: '/metadata-sources',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsLogsRoute =
  AuthenticatedSettingsLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsLiveTvRoute =
  AuthenticatedSettingsLiveTvRouteImport.update({
    id: '/live-tv',
    path: '/live-tv',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsLibraryRoute =
  AuthenticatedSettingsLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsJobsRoute =
  AuthenticatedSettingsJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDlnaRoute =
  AuthenticatedSettingsDlnaRouteImport.update({
    id: '/dlna',
    path: '/dlna',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDevicesRoute =
  AuthenticatedSettingsDevicesRouteImport.update({
    id: '/devices',
    path: '/devices',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsConsoleRoute =
  AuthenticatedSettingsConsoleRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPersonIdRoute = AuthenticatedPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaIdRoute = AuthenticatedMediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveTvChannelIdRoute =
  AuthenticatedLiveTvChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AuthenticatedLiveTvRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsOperationsRouteRoute =
  AuthenticatedSettingsOperationsRouteRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsOperationsIndexRoute =
  AuthenticatedSettingsOperationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsOperationsRouteRoute,
  } as any)
const AuthenticatedSettingsMetadataIndexRoute =
  AuthenticatedSettingsMetadataIndexRouteImport.update({
    id: '/metadata/',
    path: '/metadata/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsOperationsManageRoute =
  AuthenticatedSettingsOperationsManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AuthenticatedSettingsOperationsRouteRoute,
  } as any)
const AuthenticatedSettingsMetadataIdRoute =
  AuthenticatedSettingsMetadataIdRouteImport.update({
    id: '/metadata/$id',
    path: '/metadata/$id',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/live-tv': typeof AuthenticatedLiveTvRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/library-browser': typeof AuthenticatedLibraryBrowserRoute
  '/search': typeof AuthenticatedSearchRoute
  '/play/$id': typeof PlayIdRoute
  '/settings/operations': typeof AuthenticatedSettingsOperationsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/live-tv/$channelId': typeof AuthenticatedLiveTvChannelIdRoute
  '/media/$id': typeof AuthenticatedMediaIdRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/console': typeof AuthenticatedSettingsConsoleRoute
  '/settings/devices': typeof AuthenticatedSettingsDevicesRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/dlna': typeof AuthenticatedSettingsDlnaRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/jobs': typeof AuthenticatedSettingsJobsRoute
  '/settings/library': typeof AuthenticatedSettingsLibraryRoute
  '/settings/live-tv': typeof AuthenticatedSettingsLiveTvRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/metadata-sources': typeof AuthenticatedSettingsMetadataSourcesRoute
  '/settings/network': typeof AuthenticatedSettingsNetworkRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/playback': typeof AuthenticatedSettingsPlaybackRoute
  '/settings/plugins': typeof AuthenticatedSettingsPluginsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/scan-exclusions': typeof AuthenticatedSettingsScanExclusionsRoute
  '/settings/schedules': typeof AuthenticatedSettingsSchedulesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/subtitles': typeof AuthenticatedSettingsSubtitlesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/live-tv/': typeof AuthenticatedLiveTvIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/metadata/$id': typeof AuthenticatedSettingsMetadataIdRoute
  '/settings/operations/manage': typeof AuthenticatedSettingsOperationsManageRoute
  '/settings/metadata/': typeof AuthenticatedSettingsMetadataIndexRoute
  '/settings/operations/': typeof AuthenticatedSettingsOperationsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/library-browser': typeof AuthenticatedLibraryBrowserRoute
  '/search': typeof AuthenticatedSearchRoute
  '/play/$id': typeof PlayIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/live-tv/$channelId': typeof AuthenticatedLiveTvChannelIdRoute
  '/media/$id': typeof AuthenticatedMediaIdRoute
  '/person/$id': typeof AuthenticatedPersonIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/console': typeof AuthenticatedSettingsConsoleRoute
  '/settings/devices': typeof AuthenticatedSettingsDevicesRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/dlna': typeof AuthenticatedSettingsDlnaRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/jobs': typeof AuthenticatedSettingsJobsRoute
  '/settings/library': typeof AuthenticatedSettingsLibraryRoute
  '/settings/live-tv': typeof AuthenticatedSettingsLiveTvRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/metadata-sources': typeof AuthenticatedSettingsMetadataSourcesRoute
  '/settings/network': typeof AuthenticatedSettingsNetworkRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/playback': typeof AuthenticatedSettingsPlaybackRoute
  '/settings/plugins': typeof AuthenticatedSettingsPluginsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/scan-exclusions': typeof AuthenticatedSettingsScanExclusionsRoute
  '/settings/schedules': typeof AuthenticatedSettingsSchedulesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/subtitles': typeof AuthenticatedSettingsSubtitlesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/live-tv': typeof AuthenticatedLiveTvIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/metadata/$id': typeof AuthenticatedSettingsMetadataIdRoute
  '/settings/operations/manage': typeof AuthenticatedSettingsOperationsManageRoute
  '/settings/metadata': typeof AuthenticatedSettingsMetadataIndexRoute
  '/settings/operations': typeof AuthenticatedSettingsOperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/setup': typeof SetupRoute
  '/_authenticated/live-tv': typeof AuthenticatedLiveTvRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/library-browser': typeof AuthenticatedLibraryBrowserRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/play/$id': typeof PlayIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/operations': typeof AuthenticatedSettingsOperationsRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/live-tv/$channelId': typeof AuthenticatedLiveTvChannelIdRoute
  '/_authenticated/media/$id': typeof AuthenticatedMediaIdRoute
  '/_authenticated/person/$id': typeof AuthenticatedPersonIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/console': typeof AuthenticatedSettingsConsoleRoute
  '/_authenticated/settings/devices': typeof AuthenticatedSettingsDevicesRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/dlna': typeof AuthenticatedSettingsDlnaRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/jobs': typeof AuthenticatedSettingsJobsRoute
  '/_authenticated/settings/library': typeof AuthenticatedSettingsLibraryRoute
  '/_authenticated/settings/live-tv': typeof AuthenticatedSettingsLiveTvRoute
  '/_authenticated/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/_authenticated/settings/metadata-sources': typeof AuthenticatedSettingsMetadataSourcesRoute
  '/_authenticated/settings/network': typeof AuthenticatedSettingsNetworkRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/playback': typeof AuthenticatedSettingsPlaybackRoute
  '/_authenticated/settings/plugins': typeof AuthenticatedSettingsPluginsRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/scan-exclusions': typeof AuthenticatedSettingsScanExclusionsRoute
  '/_authenticated/settings/schedules': typeof AuthenticatedSettingsSchedulesRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/subtitles': typeof AuthenticatedSettingsSubtitlesRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/live-tv/': typeof AuthenticatedLiveTvIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/metadata/$id': typeof AuthenticatedSettingsMetadataIdRoute
  '/_authenticated/settings/operations/manage': typeof AuthenticatedSettingsOperationsManageRoute
  '/_authenticated/settings/metadata/': typeof AuthenticatedSettingsMetadataIndexRoute
  '/_authenticated/settings/operations/': typeof AuthenticatedSettingsOperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/setup'
    | '/live-tv'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/favorites'
    | '/library'
    | '/library-browser'
    | '/search'
    | '/play/$id'
    | '/settings/operations'
    | '/errors/$error'
    | '/live-tv/$channelId'
    | '/media/$id'
    | '/person/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/console'
    | '/settings/devices'
    | '/settings/display'
    | '/settings/dlna'
    | '/settings/general'
    | '/settings/jobs'
    | '/settings/library'
    | '/settings/live-tv'
    | '/settings/logs'
    | '/settings/metadata-sources'
    | '/settings/network'
    | '/settings/notifications'
    | '/settings/playback'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/scan-exclusions'
    | '/settings/schedules'
    | '/settings/security'
    | '/settings/subtitles'
    | '/settings/users'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/live-tv/'
    | '/settings/'
    | '/settings/metadata/$id'
    | '/settings/operations/manage'
    | '/settings/metadata/'
    | '/settings/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/setup'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/favorites'
    | '/library'
    | '/library-browser'
    | '/search'
    | '/play/$id'
    | '/'
    | '/errors/$error'
    | '/live-tv/$channelId'
    | '/media/$id'
    | '/person/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/console'
    | '/settings/devices'
    | '/settings/display'
    | '/settings/dlna'
    | '/settings/general'
    | '/settings/jobs'
    | '/settings/library'
    | '/settings/live-tv'
    | '/settings/logs'
    | '/settings/metadata-sources'
    | '/settings/network'
    | '/settings/notifications'
    | '/settings/playback'
    | '/settings/plugins'
    | '/settings/profile'
    | '/settings/roles'
    | '/settings/scan-exclusions'
    | '/settings/schedules'
    | '/settings/security'
    | '/settings/subtitles'
    | '/settings/users'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/live-tv'
    | '/settings'
    | '/settings/metadata/$id'
    | '/settings/operations/manage'
    | '/settings/metadata'
    | '/settings/operations'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/setup'
    | '/_authenticated/live-tv'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/favorites'
    | '/_authenticated/library'
    | '/_authenticated/library-browser'
    | '/_authenticated/search'
    | '/play/$id'
    | '/_authenticated/'
    | '/_authenticated/settings/operations'
    | '/_authenticated/errors/$error'
    | '/_authenticated/live-tv/$channelId'
    | '/_authenticated/media/$id'
    | '/_authenticated/person/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/console'
    | '/_authenticated/settings/devices'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/dlna'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/jobs'
    | '/_authenticated/settings/library'
    | '/_authenticated/settings/live-tv'
    | '/_authenticated/settings/logs'
    | '/_authenticated/settings/metadata-sources'
    | '/_authenticated/settings/network'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/playback'
    | '/_authenticated/settings/plugins'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/scan-exclusions'
    | '/_authenticated/settings/schedules'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/subtitles'
    | '/_authenticated/settings/users'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/live-tv/'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/metadata/$id'
    | '/_authenticated/settings/operations/manage'
    | '/_authenticated/settings/metadata/'
    | '/_authenticated/settings/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  SetupRoute: typeof SetupRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  PlayIdRoute: typeof PlayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/play/$id': {
      id: '/play/$id'
      path: '/play/$id'
      fullPath: '/play/$id'
      preLoaderRoute: typeof PlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library-browser': {
      id: '/_authenticated/library-browser'
      path: '/library-browser'
      fullPath: '/library-browser'
      preLoaderRoute: typeof AuthenticatedLibraryBrowserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-tv': {
      id: '/_authenticated/live-tv'
      path: '/live-tv'
      fullPath: '/live-tv'
      preLoaderRoute: typeof AuthenticatedLiveTvRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/live-tv/': {
      id: '/_authenticated/live-tv/'
      path: '/'
      fullPath: '/live-tv/'
      preLoaderRoute: typeof AuthenticatedLiveTvIndexRouteImport
      parentRoute: typeof AuthenticatedLiveTvRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/subtitles': {
      id: '/_authenticated/settings/subtitles'
      path: '/subtitles'
      fullPath: '/settings/subtitles'
      preLoaderRoute: typeof AuthenticatedSettingsSubtitlesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/schedules': {
      id: '/_authenticated/settings/schedules'
      path: '/schedules'
      fullPath: '/settings/schedules'
      preLoaderRoute: typeof AuthenticatedSettingsSchedulesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/scan-exclusions': {
      id: '/_authenticated/settings/scan-exclusions'
      path: '/scan-exclusions'
      fullPath: '/settings/scan-exclusions'
      preLoaderRoute: typeof AuthenticatedSettingsScanExclusionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/plugins': {
      id: '/_authenticated/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AuthenticatedSettingsPluginsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/playback': {
      id: '/_authenticated/settings/playback'
      path: '/playback'
      fullPath: '/settings/playback'
      preLoaderRoute: typeof AuthenticatedSettingsPlaybackRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/network': {
      id: '/_authenticated/settings/network'
      path: '/network'
      fullPath: '/settings/network'
      preLoaderRoute: typeof AuthenticatedSettingsNetworkRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/metadata-sources': {
      id: '/_authenticated/settings/metadata-sources'
      path: '/metadata-sources'
      fullPath: '/settings/metadata-sources'
      preLoaderRoute: typeof AuthenticatedSettingsMetadataSourcesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/logs': {
      id: '/_authenticated/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof AuthenticatedSettingsLogsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/live-tv': {
      id: '/_authenticated/settings/live-tv'
      path: '/live-tv'
      fullPath: '/settings/live-tv'
      preLoaderRoute: typeof AuthenticatedSettingsLiveTvRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/library': {
      id: '/_authenticated/settings/library'
      path: '/library'
      fullPath: '/settings/library'
      preLoaderRoute: typeof AuthenticatedSettingsLibraryRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/jobs': {
      id: '/_authenticated/settings/jobs'
      path: '/jobs'
      fullPath: '/settings/jobs'
      preLoaderRoute: typeof AuthenticatedSettingsJobsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/dlna': {
      id: '/_authenticated/settings/dlna'
      path: '/dlna'
      fullPath: '/settings/dlna'
      preLoaderRoute: typeof AuthenticatedSettingsDlnaRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/devices': {
      id: '/_authenticated/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof AuthenticatedSettingsDevicesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/console': {
      id: '/_authenticated/settings/console'
      path: '/console'
      fullPath: '/settings/console'
      preLoaderRoute: typeof AuthenticatedSettingsConsoleRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/person/$id': {
      id: '/_authenticated/person/$id'
      path: '/person/$id'
      fullPath: '/person/$id'
      preLoaderRoute: typeof AuthenticatedPersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/$id': {
      id: '/_authenticated/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof AuthenticatedMediaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-tv/$channelId': {
      id: '/_authenticated/live-tv/$channelId'
      path: '/$channelId'
      fullPath: '/live-tv/$channelId'
      preLoaderRoute: typeof AuthenticatedLiveTvChannelIdRouteImport
      parentRoute: typeof AuthenticatedLiveTvRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/operations': {
      id: '/_authenticated/settings/operations'
      path: '/operations'
      fullPath: '/settings/operations'
      preLoaderRoute: typeof AuthenticatedSettingsOperationsRouteRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/operations/': {
      id: '/_authenticated/settings/operations/'
      path: '/'
      fullPath: '/settings/operations/'
      preLoaderRoute: typeof AuthenticatedSettingsOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsOperationsRouteRoute
    }
    '/_authenticated/settings/metadata/': {
      id: '/_authenticated/settings/metadata/'
      path: '/metadata'
      fullPath: '/settings/metadata/'
      preLoaderRoute: typeof AuthenticatedSettingsMetadataIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/operations/manage': {
      id: '/_authenticated/settings/operations/manage'
      path: '/manage'
      fullPath: '/settings/operations/manage'
      preLoaderRoute: typeof AuthenticatedSettingsOperationsManageRouteImport
      parentRoute: typeof AuthenticatedSettingsOperationsRouteRoute
    }
    '/_authenticated/settings/metadata/$id': {
      id: '/_authenticated/settings/metadata/$id'
      path: '/metadata/$id'
      fullPath: '/settings/metadata/$id'
      preLoaderRoute: typeof AuthenticatedSettingsMetadataIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedLiveTvRouteRouteChildren {
  AuthenticatedLiveTvChannelIdRoute: typeof AuthenticatedLiveTvChannelIdRoute
  AuthenticatedLiveTvIndexRoute: typeof AuthenticatedLiveTvIndexRoute
}

const AuthenticatedLiveTvRouteRouteChildren: AuthenticatedLiveTvRouteRouteChildren =
  {
    AuthenticatedLiveTvChannelIdRoute: AuthenticatedLiveTvChannelIdRoute,
    AuthenticatedLiveTvIndexRoute: AuthenticatedLiveTvIndexRoute,
  }

const AuthenticatedLiveTvRouteRouteWithChildren =
  AuthenticatedLiveTvRouteRoute._addFileChildren(
    AuthenticatedLiveTvRouteRouteChildren,
  )

interface AuthenticatedSettingsOperationsRouteRouteChildren {
  AuthenticatedSettingsOperationsManageRoute: typeof AuthenticatedSettingsOperationsManageRoute
  AuthenticatedSettingsOperationsIndexRoute: typeof AuthenticatedSettingsOperationsIndexRoute
}

const AuthenticatedSettingsOperationsRouteRouteChildren: AuthenticatedSettingsOperationsRouteRouteChildren =
  {
    AuthenticatedSettingsOperationsManageRoute:
      AuthenticatedSettingsOperationsManageRoute,
    AuthenticatedSettingsOperationsIndexRoute:
      AuthenticatedSettingsOperationsIndexRoute,
  }

const AuthenticatedSettingsOperationsRouteRouteWithChildren =
  AuthenticatedSettingsOperationsRouteRoute._addFileChildren(
    AuthenticatedSettingsOperationsRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsOperationsRouteRoute: typeof AuthenticatedSettingsOperationsRouteRouteWithChildren
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsConsoleRoute: typeof AuthenticatedSettingsConsoleRoute
  AuthenticatedSettingsDevicesRoute: typeof AuthenticatedSettingsDevicesRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsDlnaRoute: typeof AuthenticatedSettingsDlnaRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsJobsRoute: typeof AuthenticatedSettingsJobsRoute
  AuthenticatedSettingsLibraryRoute: typeof AuthenticatedSettingsLibraryRoute
  AuthenticatedSettingsLiveTvRoute: typeof AuthenticatedSettingsLiveTvRoute
  AuthenticatedSettingsLogsRoute: typeof AuthenticatedSettingsLogsRoute
  AuthenticatedSettingsMetadataSourcesRoute: typeof AuthenticatedSettingsMetadataSourcesRoute
  AuthenticatedSettingsNetworkRoute: typeof AuthenticatedSettingsNetworkRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPlaybackRoute: typeof AuthenticatedSettingsPlaybackRoute
  AuthenticatedSettingsPluginsRoute: typeof AuthenticatedSettingsPluginsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsScanExclusionsRoute: typeof AuthenticatedSettingsScanExclusionsRoute
  AuthenticatedSettingsSchedulesRoute: typeof AuthenticatedSettingsSchedulesRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsSubtitlesRoute: typeof AuthenticatedSettingsSubtitlesRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsMetadataIdRoute: typeof AuthenticatedSettingsMetadataIdRoute
  AuthenticatedSettingsMetadataIndexRoute: typeof AuthenticatedSettingsMetadataIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsOperationsRouteRoute:
      AuthenticatedSettingsOperationsRouteRouteWithChildren,
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsConsoleRoute: AuthenticatedSettingsConsoleRoute,
    AuthenticatedSettingsDevicesRoute: AuthenticatedSettingsDevicesRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsDlnaRoute: AuthenticatedSettingsDlnaRoute,
    AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
    AuthenticatedSettingsJobsRoute: AuthenticatedSettingsJobsRoute,
    AuthenticatedSettingsLibraryRoute: AuthenticatedSettingsLibraryRoute,
    AuthenticatedSettingsLiveTvRoute: AuthenticatedSettingsLiveTvRoute,
    AuthenticatedSettingsLogsRoute: AuthenticatedSettingsLogsRoute,
    AuthenticatedSettingsMetadataSourcesRoute:
      AuthenticatedSettingsMetadataSourcesRoute,
    AuthenticatedSettingsNetworkRoute: AuthenticatedSettingsNetworkRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsPlaybackRoute: AuthenticatedSettingsPlaybackRoute,
    AuthenticatedSettingsPluginsRoute: AuthenticatedSettingsPluginsRoute,
    AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
    AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
    AuthenticatedSettingsScanExclusionsRoute:
      AuthenticatedSettingsScanExclusionsRoute,
    AuthenticatedSettingsSchedulesRoute: AuthenticatedSettingsSchedulesRoute,
    AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
    AuthenticatedSettingsSubtitlesRoute: AuthenticatedSettingsSubtitlesRoute,
    AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsMetadataIdRoute: AuthenticatedSettingsMetadataIdRoute,
    AuthenticatedSettingsMetadataIndexRoute:
      AuthenticatedSettingsMetadataIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLiveTvRouteRoute: typeof AuthenticatedLiveTvRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedLibraryBrowserRoute: typeof AuthenticatedLibraryBrowserRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMediaIdRoute: typeof AuthenticatedMediaIdRoute
  AuthenticatedPersonIdRoute: typeof AuthenticatedPersonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLiveTvRouteRoute: AuthenticatedLiveTvRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedLibraryBrowserRoute: AuthenticatedLibraryBrowserRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMediaIdRoute: AuthenticatedMediaIdRoute,
  AuthenticatedPersonIdRoute: AuthenticatedPersonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  SetupRoute: SetupRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  PlayIdRoute: PlayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
