package httpapi

import "net/http"

func (r *Router) registerStorageRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /api/v1/storage-change/diagnostics", r.handleStorageChangeDiagnostics)
	mux.HandleFunc("POST /api/v1/storage/providers/browse", r.handleBrowseStorageProvider)
	mux.HandleFunc("POST /api/v1/storage/openlist/test", r.handleTestTemporaryOpenList)
	mux.HandleFunc("POST /api/v1/storage/openlist/browse", r.handleBrowseTemporaryOpenList)
	mux.HandleFunc("POST /api/v1/storage-events", r.handleStorageEvent)
	mux.HandleFunc("GET /api/v1/media-sources", r.handleListMediaSources)
	mux.HandleFunc("POST /api/v1/media-sources", r.handleCreateMediaSource)
	mux.HandleFunc("PATCH /api/v1/media-sources/{id}", r.handleUpdateMediaSource)
	mux.HandleFunc("DELETE /api/v1/media-sources/{id}", r.handleDeleteMediaSource)
	mux.HandleFunc("POST /api/v1/media-sources/browse", r.handleBrowseMediaSource)
}

func (r *Router) registerLibraryRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /api/v1/libraries", r.handleListLibraries)
	mux.HandleFunc("POST /api/v1/libraries", r.handleCreateLibrary)
	mux.HandleFunc("GET /api/v1/libraries/{id}", r.handleGetLibrary)
	mux.HandleFunc("DELETE /api/v1/libraries/{id}", r.handleDeleteLibrary)
	mux.HandleFunc("GET /api/v1/libraries/{id}/paths", r.handleListLibraryPaths)
	mux.HandleFunc("POST /api/v1/libraries/{id}/paths", r.handleAddLibraryPath)
	mux.HandleFunc("PATCH /api/v1/libraries/{id}/paths/{path_id}", r.handleUpdateLibraryPath)
	mux.HandleFunc("GET /api/v1/libraries/{id}/policies", r.handleGetLibraryPolicies)
	mux.HandleFunc("GET /api/v1/libraries/{id}/metadata-strategy", r.handleGetLibraryMetadataStrategy)
	mux.HandleFunc("PUT /api/v1/libraries/{id}/metadata-strategy", r.handleUpdateLibraryMetadataStrategy)
	mux.HandleFunc("PUT /api/v1/libraries/{id}/policies/scan", r.handleUpdateLibraryScanPolicy)
	mux.HandleFunc("PUT /api/v1/libraries/{id}/policies/metadata", r.handleUpdateLibraryMetadataPolicy)
	mux.HandleFunc("PUT /api/v1/libraries/{id}/policies/playback", r.handleUpdateLibraryPlaybackPolicy)
	mux.HandleFunc("PUT /api/v1/libraries/{id}/policies/subtitle", r.handleUpdateLibrarySubtitlePolicy)
	mux.HandleFunc("PUT /api/v1/libraries/{id}/scan-exclusion-rules", r.handleReplaceLibraryScanExclusionRules)
	mux.HandleFunc("POST /api/v1/libraries/{id}/scan", r.handleQueueLibraryScan)
	mux.HandleFunc("GET /api/v1/libraries/{id}/items", r.handleListLibraryItems)
}

func (r *Router) registerCatalogRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /api/v1/items/{id}", r.handleGetMetadataItem)
	mux.HandleFunc("GET /api/v1/people/{id}", r.handleGetCatalogPerson)
	mux.HandleFunc("GET /api/v1/items/{id}/artwork/{kind}", r.handleGetCatalogItemArtwork)
	mux.HandleFunc("GET /api/v1/items/{id}/resources", r.handleListMetadataItemResources)
	mux.HandleFunc("GET /api/v1/items/{id}/progress", r.handleGetCatalogItemProgress)
	mux.HandleFunc("GET /api/v1/items/{id}/playback", r.handleGetCatalogPlaybackSource)
	mux.HandleFunc("GET /api/v1/items/{id}/governance", r.handleGetCatalogGovernanceWorkspace)
	mux.HandleFunc("PUT /api/v1/items/{id}/governance/fields", r.handleUpdateCatalogGovernanceField)
	mux.HandleFunc("PUT /api/v1/items/{id}/governance/images", r.handleSelectCatalogGovernanceImage)
	mux.HandleFunc("POST /api/v1/items/{id}/governance/resources/{resource_id}/links", r.handleLinkGovernanceResource)
	mux.HandleFunc("PATCH /api/v1/items/{id}/governance/resources/{resource_id}/links/{target_metadata_item_id}", r.handleUpdateGovernanceResourceLink)
	mux.HandleFunc("DELETE /api/v1/items/{id}/governance/resources/{resource_id}/links/{target_metadata_item_id}", r.handleUnlinkGovernanceResource)
	mux.HandleFunc("POST /api/v1/items/{id}/governance/metadata-merge", r.handleMergeGovernanceMetadata)
	mux.HandleFunc("POST /api/v1/items/{id}/governance/metadata-split", r.handleSplitGovernanceMetadata)
	mux.HandleFunc("PUT /api/v1/items/{id}/governance/projection-visibility", r.handleSetGovernanceProjectionVisibility)
	mux.HandleFunc("GET /api/v1/inventory-files/{id}/stream", r.handleStreamInventoryFile)
	mux.HandleFunc("GET /api/v1/inventory-files/{id}/playback", r.handleGetInventoryFilePlaybackSource)
	mux.HandleFunc("POST /api/v1/inventory-files/{id}/probe", r.handleQueueInventoryFileProbe)
	mux.HandleFunc("POST /api/v1/inventory-files/{id}/scan-exclusion", r.handleMarkInventoryFileScanExclusion)
	mux.HandleFunc("GET /api/v1/inventory-files/{id}/scan-exclusion-preview", r.handlePreviewInventoryFileFilenameExclusion)
	mux.HandleFunc("POST /api/v1/inventory-files/{id}/filename-exclusion-rule", r.handleCreateInventoryFileFilenameExclusionRule)
	mux.HandleFunc("GET /api/v1/scan-exclusions", r.handleListScanExclusions)
	mux.HandleFunc("PATCH /api/v1/scan-exclusions/{id}", r.handleSetScanExclusionEnabled)
	mux.HandleFunc("GET /api/v1/filename-exclusion-rules", r.handleListFilenameExclusionRules)
	mux.HandleFunc("PATCH /api/v1/filename-exclusion-rules/{id}", r.handleSetFilenameExclusionRuleEnabled)
	mux.HandleFunc("POST /api/v1/filename-exclusion-rules/{id}/restores", r.handleRestoreFilenameExclusionMatch)
	mux.HandleFunc("GET /api/v1/scan-exclusion-rules", r.handleListScanExclusionRules)
	mux.HandleFunc("POST /api/v1/scan-exclusion-rules", r.handleCreateScanExclusionRule)
	mux.HandleFunc("PATCH /api/v1/scan-exclusion-rules/{id}", r.handleUpdateScanExclusionRule)
	mux.HandleFunc("DELETE /api/v1/scan-exclusion-rules/{id}", r.handleDeleteScanExclusionRule)
}
